### ISSUE TITLE
Offset millis count  "_dwTickCount" to desired value for runtime retentation from eeprom

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [arduino/ArduinoCore-sam#135]
I need to store runtine in eeprom and restore into "millis()" return count.
Is it possible to change value of "[_dwTickCount](https://github.com/arduino/ArduinoCore-sam/blob/790ff2c852bf159787a9966bddee4d9f55352d15/system/libsam/source/timetick.c#L57)"?_dwTickCount

**Comment by matthijskooijman** [comment]
See also https://github.com/arduino/ArduinoCore-API/issues/69, which tracks exactly this, but more generically across all cores.

**Comment by OptifySudarshanPatil** [comment]
Closing as no real time application.
