### ISSUE TITLE
wiring_constants.h define of true/false causing trouble

### ISSUE THREAD

**Issue by thinkyhead** [arduino/ArduinoCore-sam#50]
The `wiring_constants.h` file defines `true` as `0x1` and `false` as `0x0` and this conflicts with the definition in `stdbool.h` included by `Arduino.h` (and others). The compiler bails when it hits this issue, causing builds to fail. For example…

- https://travis-ci.org/MarlinFirmware/Marlin/builds/378058672#L1537

How can this possibly be avoided or fixed?

**Comment by thinkyhead** [comment]
Seems to be something else. These aren't the primary cause.

**Comment by bblanchon** [comment]
Replacing `true` and `false` with `1` and `0` changes their type from `bool` to `int`, which breaks the overload resolution.
See https://github.com/bblanchon/ArduinoJson/issues/2181#issuecomment-2987343833 for an example.

Please reopen this issue.

**Comment by bridiver** [comment]
https://github.com/arduino/ArduinoCore-arc32/pull/2#issuecomment-3000917736
