### ISSUE TITLE
error: this 'else' clause does not guard... [-Werror=misleading-indentation]

### ISSUE THREAD

**Issue by Lauszus** [arduino/ArduinoCore-sam#69]
Due to the mix of spaces and tabs used for indentation the following lines: 
https://github.com/arduino/ArduinoCore-sam/blob/0a4c3b196a02e48e31b752a05d8c8064007874dc/cores/arduino/USB/USBCore.cpp#L688-L690 are causing the following warning:
```
/home/travis/.platformio/packages/framework-arduinosam/cores/sam/USB/USBCore.cpp: In function 'void USB_ISR()':
/home/travis/.platformio/packages/framework-arduinosam/cores/sam/USB/USBCore.cpp:688:21: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
                     else
                     ^~~~
/home/travis/.platformio/packages/framework-arduinosam/cores/sam/USB/USBCore.cpp:690:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
         UDD_Send8(EP0, 0);
         ^~~~~~~~~
```

See: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/569237654

A fix would simply be to replace all tabs with spaces or vice versa.

**Comment by arduinotech** [comment]
Fix please

**Comment by Suraj-singh999898** [comment]
Did it resolve?

**Comment by Lauszus** [comment]
@Suraj-singh999898 no: https://github.com/arduino/ArduinoCore-sam/blob/master/cores/arduino/USB/USBCore.cpp#L689-L690

**Comment by Lauszus** [comment]
Seems like this was fixed in: https://github.com/arduino/ArduinoCore-sam/commit/790ff2c852bf159787a9966bddee4d9f55352d15, so closing this issue.
