### ISSUE TITLE
Too many Global String constructs on Due

### ISSUE THREAD

**Issue by gwiken** [arduino/ArduinoCore-sam#79]
Too many Global String or C++ constructs in Due makes the software not running at all. Likewise if code amount goes over 100 Kbytes. Have used F-macro where there are constants for Serial port printing and response, this does not help. Seems like bss/data area gets broken during build on the Due board.
According to the stack pointer the stack size changes between 4 and 10 Kbytes, so this should not be a problem.

**Comment by cmaglie** [comment]
@gwiken I guess you find your solution elsewhere in the meantime, anyway:

declaring srings as `const char *` should allow to not use RAM and store strings directly in flash.

BTW from your description is not cleat if this is your issue, if you're still interested please comment further with more details, in particular an example sketch that demonstrates the problem.
